cross-build against Scala 2.11
This required to disable the specialization of the auto-generated Tuple2
instances, because scalac 2.11.0 produces invalid class files with duplicate
methods:

  java.lang.ClassFormatError: Duplicate method name&signature in class file
  spire/std/OrderProductInstances$$anon$228